//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public GIOHANG()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MaGioHang { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<bool> DaDat { get; set; }
    
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
