//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCNANG
    {
        public CHUCNANG()
        {
            this.LOAINGUOIDUNGs = new HashSet<LOAINGUOIDUNG>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
    
        public int MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<LOAINGUOIDUNG> LOAINGUOIDUNGs { get; set; }
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
